In [1]:
import torch

In [2]:
winner_tracker = torch.ones(52, 4)
state = torch.zeros(52, 52)

cat = torch.concat((state, winner_tracker), dim=1)

In [3]:
# torch.set_printoptions(threshold=10_000)
# print(cat)
# print(cat.flatten())
torch.equal(torch.unflatten(cat.flatten(), 0, (52, 56)), cat)

True

In [4]:
from utils.card_engine import Card_Game, Card_Env, unpack, get_current_suit, get_last_turn, get_legal_moves

In [5]:
game = Card_Game()
game.get_network_input()

tensor([1, 1, 0,  ..., 0, 1, 0])

In [6]:
hand, state, winner = unpack(game.get_network_input())
print(hand.shape)
print(state.shape)
print(winner.shape)

torch.Size([52])
torch.Size([52, 52])
torch.Size([52, 4])


In [7]:
hand

tensor([1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
        0, 1, 0, 1])

In [8]:
print(torch.equal(winner, torch.zeros(52, 4)))
print(torch.equal(state, torch.zeros(52, 52)))

True
True


In [9]:
print(get_last_turn(game.get_network_input()))
print(get_current_suit(game.get_network_input()))

-1
None


In [10]:

def move_to_card(move):
    return ['2','3','4','5','6','7','8','9','10','J','Q','K','A'][move % 13], ['C', 'D', 'H', 'S'][int(move / 13)]

suits = ['C', 'D', 'H', 'S']

In [12]:
game.reset()
for _ in range(52):
    state = game.get_network_input()
    print(f'last played turn: {get_last_turn(state)}')

    suit = get_current_suit(state)
    print(f'current suit: {None if suit == None else suits[suit]}')
    moves = game.get_legal_moves()
    encode_moves = torch.zeros(52)
    encode_moves[moves] = 1

    assert(torch.equal(get_legal_moves(state), encode_moves))

    i = torch.randint(len(moves), (1,))
    game.play_card(moves[i])

    print(f'played card: {move_to_card(moves[i])}')
    print()

state = game.get_network_input()
print(f'last played turn: {get_last_turn(state)}')

suit = get_current_suit(state)
print(f'current suit: {None if suit == None else suits[suit]}')
moves = game.get_legal_moves()
encode_moves = torch.zeros(52)
encode_moves[moves] = 1

assert(torch.equal(get_legal_moves(state), encode_moves))

last played turn: -1
current suit: None
played card: ('9', 'S')

last played turn: 0
current suit: S
played card: ('Q', 'S')

last played turn: 1
current suit: S
played card: ('2', 'S')

last played turn: 2
current suit: S
played card: ('10', 'S')

last played turn: 3
current suit: None
played card: ('J', 'C')

last played turn: 4
current suit: C
played card: ('10', 'C')

last played turn: 5
current suit: C
played card: ('A', 'C')

last played turn: 6
current suit: C
played card: ('6', 'C')

last played turn: 7
current suit: None
played card: ('K', 'D')

last played turn: 8
current suit: D
played card: ('2', 'D')

last played turn: 9
current suit: D
played card: ('6', 'D')

last played turn: 10
current suit: D
played card: ('8', 'D')

last played turn: 11
current suit: None
played card: ('10', 'D')

last played turn: 12
current suit: D
played card: ('4', 'D')

last played turn: 13
current suit: D
played card: ('5', 'D')

last played turn: 14
current suit: D
played card: ('Q', 'D')

las

In [12]:
hand, _, _ = unpack(game.get_network_input())

In [13]:
hand

tensor([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0])

In [29]:
print(hand.nonzero().flatten().tolist())
print(list(map(move_to_card, hand.nonzero().flatten().tolist())))
list(map(move_to_card, game.get_legal_moves()))

[4, 5, 6, 7, 12, 31, 35, 40, 41, 43, 50]
[('6', 'C'), ('7', 'C'), ('8', 'C'), ('9', 'C'), ('A', 'C'), ('7', 'H'), ('J', 'H'), ('3', 'S'), ('4', 'S'), ('6', 'S'), ('K', 'S')]


[('6', 'C'), ('7', 'C'), ('8', 'C'), ('9', 'C'), ('A', 'C')]

In [ ]:
get_legal_moves(game.get_network_input())